name: Sync OAS to ReadMe
on:
  push:
    branches:
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/rdme@6.5.0
        with:
          rdme: openapi ./petstore.json --key=${{ secrets.rdmeapikey }}
